version: '3.3'

services:
  plotlabserver:
    extends:
      file: plotlabserver/plotlabserver.yaml
      service: plotlabserver
    environment:
      # Change the display mode for plotlabserver by uncommenting the desired mode.
      #   For more information regarding display modes please refer to the plotlabserver
      #   documentation.
      - DISPLAY_MODE=${DISPLAY_MODE:-native}
      #       - DISPLAY_MODE=${DISPLAY_MODE:-window_manager}
      # - DISPLAY_MODE=${DISPLAY_MODE:-headless}
  ros-master:
    image: ros:noetic-ros-core
    container_name: ros-master
    command: stdbuf -o L roscore
    restart: always
    user: nobody
    environment:
      - "ROS_HOME=/tmp/adore/.log/.ros"
      - "ROS_MASTER_URI=http://127.0.0.1:11311"
      - "ROS_HOSTNAME=127.0.0.1"
    #volumes:
    #    - .ros:/tmp/adore/.ros
  adore-cli:
    privileged: true
    image: adore-cli:latest
    container_name: adore-cli
    user: adore-cli
    hostname: adore-cli
    network_mode: "host"
    environment:
      - CATKIN_WORKSPACE_DIRECTORY=${CATKIN_WORKSPACE_DIRECTORY:-catkin_workspace}
      - TEST_SCENARIOS=${TEST_SCENARIOS:-baseline_test.launch}
      - "ADORE_SOURCE_DIR=/tmp/adore"
      - "BAG_OUTPUT_DIRECTORY=/tmp/adore/.log/.ros/bag_files"
      - "ROS_HOME=/tmp/adore/.log/.ros"
      - "HISTFILE=/tmp/adore/.zsh_history"
      - "ROS_MASTER_URI=http://127.0.0.1:11311"
      - "ROS_HOSTNAME=127.0.0.1"
    depends_on:
      # - ros-master  #activate this option if you want to start roscore on startup of adore-cli container
       - plotlabserver  #activate this option if you want to start plotlabserver automatically with adore-cli container
    build:
      context: .
      network: host
      dockerfile: docker/Dockerfile.adore-cli
      args:
        - USER=adore-cli
        - UID=${UID:-1000}
        - GID=${GID:-1001}
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - .bash_history:/home/adore-cli/.bash_history
        - ./:/tmp/adore
  
  adore-cli-x11-display:
    privileged: true
    image: adore-cli_x11-display:latest
    container_name: adore-cli
    user: adore-cli
    hostname: adore-cli
    network_mode: "host"
    environment:
      # - DISPLAY_MODE=${DISPLAY_MODE:-native}
      - DISPLAY_MODE=${DISPLAY_MODE:-window_manager}
      #- DISPLAY_MODE=${DISPLAY_MODE:-headless}
      - CATKIN_WORKSPACE_DIRECTORY=${CATKIN_WORKSPACE_DIRECTORY:-catkin_workspace}
      - DISPLAY=${DISPLAY}
      - UID=${UID}
      - GID=${GID}
      - TEST_SCENARIOS=${TEST_SCENARIOS:-baseline_test.launch}
      - "ADORE_SOURCE_DIR=/tmp/adore"
      - "BAG_OUTPUT_DIRECTORY=/tmp/adore/.log/.ros/bag_files"
      - "ROS_HOME=/tmp/adore/.log/.ros"
      - "HISTFILE=/tmp/adore/.zsh_history"
      - "ROS_MASTER_URI=http://127.0.0.1:11311"
      - "ROS_HOSTNAME=127.0.0.1"
    depends_on:
      # - ros-master  #activate this option if you want to start roscore on startup of adore-cli container
       - plotlabserver  #activate this option if you want to start plotlabserver automatically with adore-cli container
    build:
      context: .
      network: host
      dockerfile: docker/Dockerfile.adore-cli_x11_display
      args:
        - USER=adore-cli
        - UID=${UID:-1000}
        - GID=${GID:-1001}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /var/run/docker.sock:/var/run/docker.sock
      - .bash_history:/home/adore-cli/.bash_history
      - ./:/tmp/adore
